name: Caching demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3.2.5
        env:
          cache-name: cache-node-modules
        with:          
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        
      - name: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
